version: '3'

services:
  traefik:
    image: traefik
    restart: on-failure
    container_name: traefik
    hostname: traefik
    domainname: ${DOMAINNAME}
    command: "${TRAEFIK_COMMAND}"
    environment:
      - TZ
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_HOSTED_ZONE_ID
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${PWD}/proxy/${SCHEME}.toml:/traefik.toml
      - ${PWD}/acme:/etc/traefik/acme
    ports:
      - "8080:8080"
      - "443:443"
      - "80:80"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:traefik.${DOMAINNAME}"
      - "traefik.port=8080"
      - "traefik.docker.network=web"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"

networks:
  db:
    external:
      name: db
  web:
    external:
      name: web
