version: '3'

volumes:
  postgres_data_keycloak:
    driver: local
  postgres_data_refdata:
    driver: local
  mongo_data:
    driver: local

services:
  postgres_keycloak:
    image: postgres:10-alpine
    restart: on-failure
    container_name: postgres_keycloak
    volumes:
      - postgres_data_keycloak:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  postgres_refdata:
    image: postgres:10-alpine
    restart: on-failure
    container_name: postgres_refdata
    volumes:
      - postgres_data_refdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5433:5432
  keycloak:
    image: jboss/keycloak:master
    restart: on-failure
    container_name: keycloak
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres_keycloak
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=secret
      - KEYCLOAK_IMPORT=/tmp/realm.json
      - PROXY_ADDRESS_FORWARDING=true
    volumes:
      - ${PWD}/docker/keycloak/realm.json:/tmp/realm.json
      - ${PWD}/docker/keycloak/sed.sh:/opt/jboss/startup-scripts/sed.sh
    depends_on:
      - postgres_keycloak
    ports:
      - 8081:8080
  postgrest_reference:
    image: quay.io/ukhomeofficedigital/postgrest:ho
    restart: on-failure
    container_name: postgrest_reference
    environment:
      PGRST_DB_URI: "postgres://authenticatorreference:auth1234@postgres_refdata:5432/reference"
      PGRST_DB_ANON_ROLE: webanon
      PGRST_SECRET_IS_BASE64: "false"
      PGRST_JWT_AUD: postgrest-refdata
      PGRST_ROLE_CLAIM_KEY: .refdbrole
      PGRST_DB_SCHEMA: reference
      PGRST_SERVER_PROXY_URI: "http://localhost:3000/"
      KEYCLOAK_URL: "http://keycloak:8080/keycloak"
      KEYCLOAK_REALM: refdata
    command: /bin/getKeycloakKey.sh
    depends_on:
      - postgres_refdata
      - keycloak
  postgrest_governance:
    image: quay.io/ukhomeofficedigital/postgrest:ho
    restart: on-failure
    container_name: postgrest_governance
    environment:
      PGRST_DB_URI: "postgres://authenticatorgovernance:auth1234@postgres_refdata:5432/reference"
      PGRST_DB_ANON_ROLE: webanongovernance
      PGRST_SECRET_IS_BASE64: "false"
      PGRST_JWT_AUD: postgrest-governance
      PGRST_ROLE_CLAIM_KEY: .govdbrole
      PGRST_DB_SCHEMA: governance
      PGRST_SERVER_PROXY_URI: "http://localhost:3000/"
      KEYCLOAK_URL: "http://keycloak:8080/keycloak"
      KEYCLOAK_REALM: refdata
    command: /bin/getKeycloakKey.sh
    depends_on:
      - postgres_refdata
      - keycloak
  mongo:
    image: quay.io/ukhomeofficedigital/githelper:latest
    restart: on-failure
    container_name: mongo
    entrypoint:
      - /usr/bin/mongod
      - --config
      - /config/mongod.conf
    volumes:
      - ${PWD}/docker/mongo/mongod.conf:/config/mongod.conf
      - mongo_data:/data
  formio:
    image: quay.io/ukhomeofficedigital/formio:develop
    restart: on-failure
    container_name: formio
    environment:
      MONGO_HIGH_AVAILABILITY: 0
      DB_SECRET: "potato"
      PORT: 3003
      USER_FORM: "admin"
      USER_LOGIN_FORM: "admin/login"
      PROJECT_TEMPLATE: "default"
      DOMAIN: "http://localhost:8080/formio/"
      APIDOMAIN: "http://localhost:8080/formio/"
      ROOT_EMAIL: "dev1@local"
      ROOT_PASSWORD: "password"
      MONGO: "mongodb://mongo:27017/formio"
      MONGO_SECRET: "fudge"
      JWT_SECRET: "password"
    depends_on:
      - mongo
  translation:
    image: quay.io/ukhomeofficedigital/cop-private-translation-service:develop
    restart: on-failure
    container_name: translation
    environment:
      FORM_URL: "http://formio:3001"
      PLATFORM_DATA_URL: "http://localhost:8080"
      WORKFLOW_URL: "http://workflow:8080"
      AUTH_CLIENT_ID: "translation"
      AUTH_REALM: "refdata"
      AUTH_URL: "http://keycloak:8080/keycloak/auth"
    depends_on:
      - keycloak
      - postgrest_reference
      - workflow
      - formio
  proxy:
    image: openresty/openresty:alpine-fat
    restart: on-failure
    container_name: proxy
    depends_on:
      - keycloak
      - postgrest_governance
      - postgrest_reference
      - formio
    volumes:
      - ${PWD}/docker/proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80

networks:
  default:
    external:
      name: local_dev