---
version: '3'

volumes:
  mongo_data:
    driver: local

  mongo:
    image: quay.io/ukhomeofficedigital/githelper:latest
    restart: on-failure
    container_name: mongo
    entrypoint:
      - /usr/bin/mongod
      - --config
      - /config/mongod.conf
    volumes:
      - ${PWD}/docker/mongo/mongod.conf:/config/mongod.conf
      - mongo_data:/data
  formio:
    image: quay.io/ukhomeofficedigital/formio:develop
    restart: on-failure
    container_name: formio
    environment:
      MONGO_HIGH_AVAILABILITY: 0
      DB_SECRET: "potato"
      PORT: 3003
      USER_FORM: "admin"
      USER_LOGIN_FORM: "admin/login"
      PROJECT_TEMPLATE: "default"
      DOMAIN: "http://localhost:8080/formio/"
      APIDOMAIN: "http://localhost:8080/formio/"
      ROOT_EMAIL: "dev1@local"
      ROOT_PASSWORD: "password"
      MONGO: "mongodb://mongo:27017/formio"
      MONGO_SECRET: "fudge"
      JWT_SECRET: "password"
    depends_on:
      - mongo
  translation:
    image: quay.io/ukhomeofficedigital/cop-private-translation-service:develop
    restart: on-failure
    container_name: translation
    environment:
      FORM_URL: "http://formio:3001"
      PLATFORM_DATA_URL: "http://localhost:8080"
      WORKFLOW_URL: "http://workflow:8080"
      AUTH_CLIENT_ID: "translation"
      AUTH_REALM: "refdata"
      AUTH_URL: "http://keycloak:8080/keycloak/auth"
    depends_on:
      - keycloak
      - postgrest_reference
      - workflow
      - formio