version: '3'


volumes:
  postgres_data_keycloak:
    driver: local


services:
  postgres_keycloak:
    image: postgres:10-alpine
    restart: on-failure
    container_name: postgres_keycloak
    volumes:
      - postgres_data_keycloak:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: jboss/keycloak:master
    restart: on-failure
    container_name: keycloak
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres_keycloak
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=secret
      - KEYCLOAK_IMPORT=/tmp/realm.json
      - PROXY_ADDRESS_FORWARDING=true
    volumes:
      - ${PWD}/keycloak/dev/dev-realm.json:/tmp/realm.json
      - ${PWD}/keycloak/sed.sh:/opt/jboss/startup-scripts/sed.sh
    depends_on:
      - postgres_keycloak
    ports:
      - 8081:8080

  proxy:
    image: openresty/openresty:alpine-fat
    restart: on-failure
    container_name: proxy
    depends_on:
      - keycloak
    volumes:
      - ${PWD}/proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80

networks:
  default:
    external:
      name: local_dev
