---
apiVersion: v1
kind: Secret
metadata:
  name: {{.NAME}}
type: Opaque
data:
  authClientSecret: "{{.KEYCLOAK_SECRET | b64enc }}"
  sessionName: "{{.SESSION_NAME | b64enc }}"
  sessionSecret: "{{.SESSION_SECRET | b64enc }}"